config/routes.rb
ArasBlog::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root "home#index"
  
  resources :blogs, :only => :show do
    resources :posts, :only => :show
  end
  resources :landing_pages, :only => :show
  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  belongs_to :user
  has_many :posts
  
  mount_uploader :image, PhotoUploader
  
  validates :name, :user_id, :presence => true
  validates :priority, :numericality => {:integer_only => true }

end

app/models/briefing.rb
class Briefing < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  
  validates :headline, :description, :presence => true
  validates :position, :numericality => {:only_integer => true}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/landing_page.rb
class LandingPage < ActiveRecord::Base
  extend FriendlyId
  friendly_id :headline, use: :slugged
  
  mount_uploader :image, PhotoUploader
  
  belongs_to :landing_page_type
  
  validates :headline, :description, :landing_page_type_id, :presence => true
end

app/models/landing_page_type.rb
class LandingPageType < ActiveRecord::Base
  has_many :landing_pages
  
  validates :name, :presence => true
  
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :file, PhotoUploader
  
  validates :file, :presence => true
  
  def url
    file.to_s
  end
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :headline, use: :slugged
  
  mount_uploader :image, ImageUploader
  
  belongs_to :user
  belongs_to :blog
  
  validates :headline, :introduction, :blog_id, :user_id, :publication_date, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable
     
  validates :first_name, :last_name, :presence => true
      
  def name
    [first_name, last_name].join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :initalize_navigation
  
  private
  def initalize_navigation
    @blogs = Blog.where("active = ?", true).order("priority ASC")
    @navigation_pages = LandingPage.joins(:landing_page_type)
                        .where("landing_pages.active = ? AND landing_page_types.name = ?", true, "Navigation").order("headline")
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  
  def show
    @blog = Blog.friendly.find(params[:id])
    @posts = @blog.posts.order("publication_date DESC")
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @posts = Post.where("active = ? AND featured = ?", true, true).order("publication_date DESC")
    @briefings = Briefing.where("active = ?", true).order("position").all
  end
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
  
  def show
    @page = LandingPage.friendly.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def show
    @blog = Blog.friendly.find(params[:blog_id])
    @post = @blog.posts.friendly.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/show.html.erb
<div class="container-fluid">
  <div class="row" style="position:relative;">
    <p><%= image_tag(@blog.image, :alt => @blog.name, :class => "img-responsive", :style => "margin:auto;") %></p>
    <h2 style='font-size:6rem;color:white;font-family:"Dancing Script",Helvetica,sans-serif;position:absolute;bottom:150px;width:100%;' class="text-center"><%= @blog.name %></h2>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12" style="font-size:1.8rem;margin:20px;">
      <div class="text-center">
        <%= @blog.introduction.to_s.html_safe %>
      </div>
    </div>
  </div>
  
  <%= @posts.each_slice(3) do |slice| %>
    <div class="row">
      <% slice.each do |post| %>
        <div class="col-xs-12 col-sm-4">
          <div style="position:relative;">
            <p><%= image_tag(post.image, :alt => post.headline, :class => "img-responsive") %></p>
            <div style="background-color:pink;position:relative;padding:10px 20px;width:80%;left:2%;bottom:20px;">
              <h3><%= link_to post.headline, blog_post_path(@blog, post) %></h3>
              <p><%= post.publication_date.strftime("%d/%m/%Y") %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<style>
.homepage-slider :focus {
  outline: none;
}
</style>

<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="homepage-slider">
        <% @posts.each do |post| %>
          <div>
            <div class="row">
              <div class="col-xs-12 col-sm-7">
                <p><%= link_to image_tag(post.image, :alt => post.headline, :class => "img-responsive"), blog_post_path(post.blog, post) %></p>
              </div>
              <div class="col-xs-12 col-sm-5">
                <div style="padding-right:10px;">
                  <h2 style="margin-top: 5px;"><%= link_to post.headline, blog_post_path(post.blog, post) %></h2>
                  <div class="introduction" style="font-size: 1.8rem;">
                    <%= post.introduction.to_s.html_safe %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <div style="margin-top:60px;margin-bottom:30px;">
        <% if @briefings.any? %>
          <% @briefings.each_slice(2) do |slice| %>
            <div class="row">
              <% slice.each do |briefing| %>
                <div class="col-xs-12 col-sm-6">
                  <% if briefing.image.present? %>
                    <p><%#= image_tag(briefing.image, :alt => briefing.headline, :class => "img-responsive" )%></p>
                  <% end %>
                  <h3 class="text-center"><%= briefing.headline %></h3>
                  <div class="description" style="padding-bottom:20px;">
                    <%= briefing.description.to_s.html_safe %>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/landing_pages/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <p><%= image_tag(@page.image, :alt => @page.headline, :class => "img-responsive", :style => "margin:auto;" )%>
      <h2 class="text-center"><%= @page.headline %></h2>
      <hr />
      <div><%= @page.description.to_s.html_safe %></div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>ArasBlog</title>
  
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
      
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,700,300,400italic,700italic,300italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Dancing+Script:400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.5.7/slick.css"/>
  
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default visible-xs-block">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="bs-navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="<%= 'active' if controller_name == "home" %>"><a href="/">Home</a></li>
      		<% @blogs.each do |blog| %>
            <li class="<%= 'active' if controller_name =~ /blogs|posts/ && @blog.slug == blog.slug %>"><%= link_to blog.name, blog_path(blog)%></li>
      		<% end %>
      		<% @navigation_pages.each do |page| %>
      			<li class="<%= 'active' if controller_name == "landing_pages" && @page.slug == page.slug %>"><%= link_to page.headline, landing_page_path(page) %>
      		<% end %>
        </ul>
      </div>
    </div>
  </nav>
  
  <div class="container-fluid text-center">
    <div class="row header">
      <div class="col-xs-5 text-right">
        <p><%= image_tag("ara-headshot.png", :alt => "Ara", :width => "80") %></p>
      </div>
      <div class="col-xs-7 text-left">
        <h1><span>Japanese &amp; Language</span><br /> <em>Experiments</em></h1>
      </div>
    </div>
  </div>
  
  <nav class="navbar navbar-default hidden-xs text-center">
    <div class="container-fluid">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if controller_name == "home" %>"><a href="/">Home</a></li>
    		<% @blogs.each do |blog| %>
          <li class="<%= 'active' if controller_name =~ /blogs|posts/ && @blog.slug == blog.slug %>"><%= link_to blog.name, blog_path(blog)%></li>
    		<% end %>
    		<% @navigation_pages.each do |page| %>
    			<li class="<%= 'active' if controller_name == "landing_pages" && @page.slug == page.slug %>"><%= link_to page.headline, landing_page_path(page) %>
    		<% end %>
      </ul>
    </div>
  </nav>

  <%= yield %>
  
  <div class="container-fluid" style="margin-top:20px;">
    <div class="row">
  	  <footer style="background-color:#DB5A6B;padding:10px;color:white;font-size:1.5rem;width:100%">
  		  <p class="text-center" style="margin:10px;">Contact: <a href="mailto:sinzoko@hotmail.com" style="color:white;">sinzoko@hotmail.com</a></p>
  	  </footer>
    </div>
  </div>
</body>
</html>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-2">
      <h4 class="text-right"><%= @post.publication_date.strftime("%d/%m/%Y") %></h4>
    </div>
    <div class="col-xs-12 col-sm-10" style="border-left: 1px solid #DB5A6B;">
      <p><%= image_tag(@post.image, :alt => @post.headline, :class => "img-responsive", :style => "margin:auto;" )%>
      <h2 class="text-center"><%= @post.headline %></h2>
      <hr />
      <div><%= @post.introduction.to_s.html_safe %></div>
      
      <div><%= @post.description.to_s.html_safe %></div>
    </div>
  </div>
</div>